# paths to ignore during linting
disabled_rules:
  - operator_whitespace
  - multiple_closures_with_trailing_closure
trailing_comma:
  severity: warning
  mandatory_comma: true
identifier_name:
  # warning, not errors for shorter names to not break the project
  min_length: 3
  max_length: 45
  allowed_symbols: ["_"]
  excluded:
    - id
    - up
    - h1
    - h2
    - h3
    - on
nesting:
  type_level: 4
