pr:
- main

variables:
  - group: "SatsVariables"
  - name: "scheme"
    value: "DemoApp"
  - name: "sdk"
    value: "iphoneos"

pool:
  vmImage: "macos-latest"

jobs:
  - job: BuildDev
    displayName: Build SATS Dev
    steps:          
      - task: Xcode@5
        displayName: "Xcode Test"
        inputs:
          actions: "clean build test"
          sdk: "$(sdk)"
          scheme: "$(scheme)"
          xcodeVersion: "default"
          destinationSimulators: "iPhone 12 Pro"
          workingDirectory: "DemoApp"
