pr:
- main

variables:
  - group: "SatsVariables"
  - name: "scheme"
    value: "DemoApp"
  - name: "sdk"
    value: "iphoneos"

pool:
  vmImage: "macos-latest"

jobs:
  - job: BuildDev
    displayName: Build SATS Dev
    steps:          
      - task: Xcode@5
        displayName: "Xcode Test"
        inputs:
          actions: "test"
          sdk: "$(sdk)"
          scheme: "$(scheme)"
          xcodeVersion: "default"
          xcWorkspacePath: "DemoApp/DemoApp.xcodeproj"
          destinationPlatform: "iOS"
          signingOption: "auto"
          args: "-UseModernBuildSystem=YES"
          destinationPlatformOption: "iOS"
          destinationSimulators: "iPhone 12 Pro,OS=14.4"
          workingDirectory: "DemoApp"
          useXcpretty: true
          publishJUnitResults: true
